version: '3.9'

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services: 
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: 'toor'
      POSTGRES_USER: 'docker'
    networks:
      network:
        ipv4_address: 10.5.0.4
  api:
    build: ./backend
    ports:
      - '3000:3000'
    networks:
      network:
        ipv4_address: 10.5.0.5
  web:
    build: ./frontend
    ports:
      - '3001:3001'
    networks:
      network:
        ipv4_address: 10.5.0.3

volumes:
  postgres_data: